{% set version = "1.3.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlas
  version: {{ version|replace("-", "_") }}

source:
  fn: rlas_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rlas_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rlas/rlas_{{ version }}.tar.gz
  sha256: d802e293995c4246faa4019d59400458621532eda5fad445d16412be27a7a169

build:
  merge_build_host: True  # [win]
  script: R CMD INSTALL --build .
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-data.table
    - r-rgeos
    - r-sf
    - r-sp
    - r-uuid
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-rcpp
    - r-data.table
    - r-rgeos
    - r-sf
    - r-sp
    - r-uuid

test:
  commands:
    - $R -e "library('rlas')"           # [not win]
    - "\"%R%\" -e \"library('rlas')\""  # [win]

about:
  home: https://github.com/Jean-Romain/rlas
  license: GPL-3
  summary: Read and write 'las' and 'laz' binary file formats. The LAS file format is a public
    file format for the interchange of 3-dimensional point cloud data between data users.
    The LAS specifications are approved by the American Society for Photogrammetry and
    Remote Sensing <https://www.asprs.org/committee-general/laser-las-file-format-exchange-activities.html>.
    The LAZ file format is an open and lossless compression scheme for binary LAS format
    versions 1.0 to 1.3 <https://www.laszip.org/>.
  license_family: GPL3

extra:
  recipe-maintainers:
    - ocefpaf
