{% set version = "1.2.3" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlas
  version: {{ version }}

source:
  fn: rlas_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rlas_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rlas/rlas_{{ version }}.tar.gz
  sha256: ee3471ed2829f14f531d1f2f6f2172b10ef04e98170c112d9fffde0950059a6f

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp
    - r-data.table
    - r-uuid
    - posix  # [win]
    - {{native}}toolchain  # [win]
    - gcc  # [not win]

  run:
    - r-base
    - r-rcpp
    - r-data.table
    - r-uuid
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('rlas')"  # [not win]
    - "\"%R%\" -e \"library('rlas')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rlas
  license: GPL-3
  summary: Read and write 'las' and 'laz' binary file formats. The LAS file format is a public
    file format for the interchange of 3-dimensional point cloud data between data users.
    The LAS specifications are approved by the American Society for Photogrammetry and
    Remote Sensing <https

extra:
  recipe-maintainers:
    - ocefpaf
