{% set version = "1.8.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rlas
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rlas_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rlas/rlas_{{ version }}.tar.gz
  sha256: dc7903cfcebcd8c0313e101cae732c8ef7b5839318799c1d3d7b778fa178143b

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-data.table
  run:
    - r-base
    - r-rcpp
    - r-data.table

test:
  commands:
    - $R -e "library('rlas')"           # [not win]
    - "\"%R%\" -e \"library('rlas')\""  # [win]

about:
  home: https://github.com/r-lidar/rlas
  license: GPL-3.0-only
  summary: Read and write 'las' and 'laz' binary file formats. The LAS file format is a public file format for the interchange of 3-dimensional point cloud data between data users. The LAS specifications are approved by the American Society for Photogrammetry and Remote Sensing <https://www.asprs.org/committee-general/laser-las-file-format-exchange-activities.html>.
    The LAZ file format is an open and lossless compression scheme for binary LAS format versions 1.0 to 1.3 <https://www.laszip.org/>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
