{% set version = "1.2.7" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlas
  version: {{ version }}

source:
  fn: rlas_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rlas_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rlas/rlas_{{ version }}.tar.gz
  sha256: 8cd5577a6c3feddd4e5b1f93cd226fea835f7ff3cfddef3e6d7a8b6e62fbb740

build:
  merge_build_host: True  # [win]
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp
    - r-data.table
    - r-uuid

  run:
    - r-base
    - r-rcpp
    - r-data.table
    - r-uuid

test:
  commands:
    - $R -e "library('rlas')"  # [not win]
    - "\"%R%\" -e \"library('rlas')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rlas
  license: GPL-3
  summary: Read and write 'las' and 'laz' binary file formats. The LAS file format is a public
    file format for the interchange of 3-dimensional point cloud data between data users.
    The LAS specifications are approved by the American Society for Photogrammetry and
    Remote Sensing <https

extra:
  recipe-maintainers:
    - ocefpaf
