travis:
  secure:
    BINSTAR_TOKEN: t3E8I3SXqVi4Q7uE5z7iHcyA0w6hFzgFhgfq/K+VcWGcu8NFJiK1UBn1UhdZslSMSot6w0V00JFQ8rZL0+kO7xqEVaC2pXvqQeaaZ34VW4fXZcRK/i7i5isIhV4mbo0JcHFxWX6nL+hoepbhL/3L8wXhDM5BiEARvqpGfNj7UQJbDzj86hqeiuuuqJD1Ex2R+Yuk60elnIJuun9fyZWwVvfuhNwY+37HHl6RD+CRlv1s3CH5eHG93tIuBOsBzG5Zlsv3/pdHbC1HH+crb/S3BTY+8McEAs1ii0cnkD/o8Y15LDTM0MKhG+vT37HUlKtYCeCWzo/hzcwsRRHQVIsY9jLOtM1zOeiWglkZadHhdtVDbc5A52fOp6nkUcUr0o9ona4ntLmKrVcSqez5LbEMyA+8FDqQF9WojIhz4kQAga62s7MYPwIOjBYq1I4tG9THnd1DkJ+SD7dIH9z8NXgO3ASFZUJQEwzllh1PHNU25hboSazxD7p/W+pnT5co0IXHWIUOSK9vi2SYBBnhE76k0ViYnAI6TS2MiuwJjvxjVFRIlx7drqxX/5kE3w/8kBLFCxuBj4pdNhytEyYrouKBf1Xg+b7yhk6l6G9HJx5XntbGkw1BpTtd5uWceFC0el9hqHV6Bz8bHSuN8HbvUCXKU96kTH9RT3fdS/YclTTqJ4g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
