appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Qe80GTWYORhecd1xbTHDY2SJu5zCZ7QJSUdtw5GAx9SYIEnNogiWi3n9XrkUNe6wtbjBfUKDzm2EUo+4b79ySeA84je4/xxVJNFDHEhreaqoHF1TvbsBS29gnDJnJV7WLsV0+bMObI2yve+KnaPN7nuoJ2ANGUEQtQsEFWbQCHN4AgOHpPl44OuVfUgfALT2uWTbHzzCHHGVt/NlC404qDr8DEqaUMUCNFx6WtSnBmRr1VkxnpVo37/PJSCKG1/zecF+WHRG5qqB4Q/ceAhBMGaHfg7soaqpM0FkX5njPn04NvZaLRgQi/Ml9p4RebZ+xuxH8sc9HWPBUlvZncdD1R7hSwiAy5dCu9pWHao4atAk/0QjrdSteWq4lE0Wm0sdHLv8x2rFt8MD2JS8H0fO+0nreWyjJ4MzF8h8BEz2Y0v32hYJ9GFSn4ZOAfihjlhSxWBWfbGn7OD33PJ+ioW4/RizEn98zy7RNR1GGyI//WpwhohXx1HBp48zRiyfRu59LGucRsRJs1bFINR4buDokS9Iva9r0uO9jV42EW0gtlG1o/QWp4TfjalM468tFDpCL+xqnVyAVDg+XTso0vz9cWUeVYFt0o/ONFRqKRFJHfIHbmViMo1S2eR4ESpvFJKgQrT9f6TBlJqjXauQmmME1ImiWkO7ISbbWRilmjIimX4=
